language: node_js
node_js:
    - 8

before_script:
    - echo $TRAVIS_COMMIT
    - echo $TRAVIS_TAG
    - echo $TRAVIS_BRANCH
    - echo $TRAVIS_BUILD_NUMBER
    - echo $TRAVIS_REPO_SLUG
  
script:
    # Lint, build UI
    - npm install
    - npm run lint
    - npm run build
